test/protocol_control.c: fix build against gcc-14 (-Walloc-size)
`gcc-14` added a new `-Walloc-size` warning that makes sure that size of
an individual element matches size of a pointed type:

    https://gcc.gnu.org/PR71219

`waypipe` triggers it on `calloc()` calls where member size is used as
`1` (instead of member count):

    test/protocol_control.c: In function 'make_filled_pattern':
    test/protocol_control.c:71:25: error: allocation of insufficient size '1'
     for type 'uint32_t' {aka 'unsigned int'} with size '4' [-Werror=alloc-size]
       71 |         uint32_t *mem = calloc(size, 1);
          |                         ^~~~~~